### ISSUE TITLE
Only pushing Pokemon name

### ISSUE THREAD

**Issue by DigitalPhoneme** [brady-newhard/js-objects-lab#1]
https://github.com/brady-newhard/js-objects-lab/blob/ee5ee5e53fcc24fadde45f41522343a8cdc8b06b/app.js#L80

Hey Brady, so you are only pushing the Pokemon name here not the whole object. that means you don't have access to other attributes when working with your ```party``` array.

**Comment by brady-newhard** [comment]
Corrected. Makes sense. I was pushing just the name to make the console log cleaner with names only.
