### ISSUE TITLE
Quantity management outside loop

### ISSUE THREAD

**Issue by DigitalPhoneme** [brady-newhard/js-objects-lab#2]
https://github.com/brady-newhard/js-objects-lab/blob/ee5ee5e53fcc24fadde45f41522343a8cdc8b06b/app.js#L170

 The ```pokeballQuantity``` is being managed outside the function, and the for loop has some incorrect logic. Make sure to correctly update ```pokeball``` quantity by checking directly in the ```game.items array```. This makes your code efficient and easy to read.
 
 ```game.catchPokemon = function(pokemonObj) {
  game.party.push(pokemonObj);
  const pokeball = game.items.find(item => item.name === "pokeball");
  if (pokeball) pokeball.quantity--;
};
```

**Comment by brady-newhard** [comment]
Corrected.  I struggled with this one. I wasn't familiar with the find method. I'll study it a bit more.
