### ISSUE TITLE
Reset gymTally

### ISSUE THREAD

**Issue by DigitalPhoneme** [brady-newhard/js-objects-lab#3]
https://github.com/brady-newhard/js-objects-lab/blob/ee5ee5e53fcc24fadde45f41522343a8cdc8b06b/app.js#L221

```gymStatus ``` is almost there! Currently, ``` gymTally ```will increment each time the method is called. Reset ```gymTally``` within the method so it counts accurately each time it’s run
 
 ```game.gymStatus = function () {
  const gymTally = { completed: 0, incomplete: 0 };
  game.gyms.forEach(gym => {
    if (gym.completed) {
      gymTally.completed++;
    } else {
      gymTally.incomplete++;
    }
  });
  console.log(gymTally);
};
```

**Comment by brady-newhard** [comment]
Corrected. Yes! This is much easier and I have begun to use this logic.
