### ISSUE TITLE
return count

### ISSUE THREAD

**Issue by DigitalPhoneme** [brady-newhard/js-objects-lab#4]
https://github.com/brady-newhard/js-objects-lab/blob/ee5ee5e53fcc24fadde45f41522343a8cdc8b06b/app.js#L245

Remember that ```partyCount``` should return the count instead of logging it directly. This way, it behaves like a method you can use within other parts of the code if needed.

```game.partyCount = function () {
  return game.party.length;
};
console.log("Exercise 14:", game.partyCount());
```

**Comment by brady-newhard** [comment]
Corrected. This makes more sense.
